apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: r2devops-postgresql
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: postgresql
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 18.1.15 # Replace with the postgresql version you'd like to install or upgrade to
      helm:
        valueFiles: 
        - $values/r2devops-postgresql-values.yaml
    - repoURL: 'https://github.com/wartoz/r2devops.git'
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: r2devops